function userLabs(userID,data){let flag=!0;for(let x of data.allowed_user_locations){if(x.user_id===userID){let lab=data.locations.find(l=>l.id===x.location_id);let labName=lab.name;let checkedStatus=flag?"checked":"";document.getElementById("lab-list").innerHTML=document.getElementById("lab-list").innerHTML+`<li><input type="radio" id="lab${lab.id}" name="lab" ${checkedStatus} onClick='labItems(${lab.id}, ${JSON.stringify(data)})'><label for="lab${lab.id}">${labName}</label></li>`;if(flag){labItems(lab.id,data);flag=!1}}}}
async function labItems(labName,currentPage=1,searchValue=""){const checkoutPanel=document.getElementsByClassName('right-sidebar')[0];if(checkoutPanel)
checkoutPanel.style.display='none';const pagination=await fetch(`../backend/queries/totalItems.php?locationName=${labName}&name=${searchValue}`).then((res)=>res.json());const totalPages=Math.ceil(pagination.totalItems/10);$("#pagination").html("");if(totalPages>1){for(let i=1;i<=totalPages;i++){$("#pagination").append(`<button class="page-button" ${currentPage === i ? "disabled" : ""} 
        onclick="labItems('${labName}', ${i}, '${searchValue}')">${i}
      </button>`)}}
const items=await fetch(`../backend/queries/filterItems.php?locationName=${labName}&page=${currentPage}&name=${searchValue}`).then((res)=>res.json());let labItems="";for(let item of items){let status=item.stock>0?"Available":"Unavailable";let type=item.borrowable?"Borrowable":"Removable";let tagClass=type==="Borrowable"?"tag tag-borrowable":"tag tag-removable";let statusClass=status==="Available"?"tag status-available":"tag status-unavailable";labItems+=`<tr id="${item.id}">
      <td class="item-name">${item.name}</td>
      <td><span class="${tagClass}">${type}</span></td>
      <td><span class="${statusClass}">${status}</span></td>
    </tr>`}
$("#lab-name").html(labName);$("#lab-items").html(labItems)}
async function search(event=null){if(event){if(event.key!=='Enter'){return}}
const searchValue=document.getElementById('search').value;await labItems(document.getElementById('lab-name').textContent,1,searchValue)}
async function populateItemDetails(labLocation,itemId){const item=await fetch(`../backend/queries/itemDetail.php?id=${itemId}`).then((res)=>res.json());const itemTitleText=document.getElementById('item-title-text');const itemTypeContainer=document.getElementById('item-type');const typeDescriptions=itemTypeContainer.getElementsByClassName('item-status');const itemBorrowableText=typeDescriptions[0];const itemStatusContainer=document.getElementById('item-status');const statusDescriptions=itemStatusContainer.getElementsByClassName('item-status');const itemStatusText=statusDescriptions[0];const itemQuantityText=document.getElementById('item-quantity-text');const descriptionText=document.getElementById('item-description-list');const checkoutButton=document.getElementById('checkout-button');itemTitleText.textContent=item.name;if(item.borrowable==0){itemBorrowableText.textContent="Removable";itemBorrowableText.style.backgroundColor='#0f78f1'}else{itemBorrowableText.textContent="Borrowable";itemBorrowableText.style.backgroundColor='#778DA9'}
if(item.stock>0){itemStatusText.textContent="In Stock";itemStatusText.style.backgroundColor="lightgreen";checkoutButton.textContent="CHECK OUT";checkoutButton.style.backgroundColor="lightgreen";checkoutButton.style.cursor="pointer"}else{itemStatusText.textContent="Out Of Stock";itemStatusText.style.backgroundColor="red";checkoutButton.textContent="UNAVAILABLE";checkoutButton.style.backgroundColor="lightcoral";checkoutButton.style.cursor="not-allowed"}
itemQuantityText.textContent=item.stock;if(item.description===""||item.description===null){descriptionText.textContent="No Description Provided."}else{descriptionText.textContent=item.description}
checkoutButton.onclick=function(){checkout(itemId,item.stock)};const deleteButton=document.getElementById("delete-button");if(deleteButton!==null){deleteButton.onclick=function(){const labName=document.getElementById('lab-name').textContent;const currentPage=parseInt(document.querySelector('#pagination button[disabled]')===null?1:document.querySelector('#pagination button[disabled]').textContent);const searchValue=document.getElementById('search').value;delete_item(labName,itemId,currentPage,searchValue)}}}
function populate(){const table=document.getElementById('item-table');const checkoutPanels=document.getElementsByClassName('right-sidebar');const checkoutPanel=checkoutPanels[0];const closePanel=document.getElementById('go-back');table.addEventListener('click',async function(event){event.preventDefault();if(event.target.tagName==='TD'&&(window.location.href.includes("user")||document.getElementsByClassName('tab-button')[0]?.id==='chosen')){checkoutPanel.style.display='flex';checkoutPanel.classList.remove('hidden');checkoutPanel.classList.add('visible');const labName=document.getElementById('lab-name').textContent;const allTDs=document.querySelectorAll('tr');allTDs.forEach(tr=>{if(tr.className==='highlighted'){tr.removeAttribute('class')}});const trElement=event.target.parentElement;trElement.className='highlighted';const itemId=trElement.id;await populateItemDetails(labName,itemId)}});closePanel.addEventListener('click',function(){checkoutPanel.classList.remove('visible');checkoutPanel.classList.add('hidden');const allTDs=document.querySelectorAll('tr');allTDs.forEach(tr=>{if(tr.className==='highlighted'){tr.removeAttribute('class')}})})}
async function checkout(id,stock){const cancelCheckoutFormButtn=document.getElementById('cancel-checkout-form-button');cancelCheckoutFormButtn.addEventListener('click',function(){const checkoutForm=document.getElementById('form-object');checkoutForm.reset();const formContainer=document.getElementById('checkout-form');formContainer.style.display="none"});const checkoutButton=document.getElementById('checkout-button');if(checkoutButton.textContent!="UNAVAILABLE"){const checkoutForm=document.getElementById('checkout-form');checkoutForm.style.display="flex";const checkoutFormTitle=document.getElementById('form-title');const itemTitleContainer=document.getElementById('item-title-text');const itemTitle=itemTitleContainer.textContent;checkoutFormTitle.textContent="Checkout "+itemTitle;const quantityEl=document.getElementById("quantity");quantityEl.setAttribute('max',stock);checkoutForm.onsubmit=function(e){e.preventDefault();finalCheckout(id)};const itemTypeText=document.getElementById('item-type-text').textContent;if(itemTypeText==="Borrowable"){document.getElementById('returnDateLabel').style.display="";document.getElementById('returnDateBreak1').style.display="";document.getElementById('returnDateBreak2').style.display="";const returnDateInput=document.getElementById('returnDate');returnDateInput.style.display="";returnDateInput.setAttribute('required','required');const currentDate=new Date();const maxReturnDate=new Date();maxReturnDate.setDate(currentDate.getDate()+14);const maxDateString=maxReturnDate.toISOString().split('T')[0];returnDateInput.setAttribute('max',maxDateString);returnDateInput.setAttribute('min',currentDate.toISOString().split('T')[0]);document.getElementById('agreeReturnLabel').textContent="I understand that I have a responsibility to return the item within 2 weeks of the reservation.";document.getElementById('agreeNotifyLabel').textContent="I understand that if I want to change the return date, I have to notify the lab administrator."}else{document.getElementById('returnDateLabel').style.display="none";document.getElementById('returnDateBreak1').style.display="none";document.getElementById('returnDateBreak2').style.display="none";const returnDateInput=document.getElementById('returnDate');returnDateInput.style.display="none";if(returnDateInput.hasAttribute('required')){returnDateInput.removeAttribute('required')}
document.getElementById('agreeReturnLabel').textContent="I understand that I do not have to return this item back to lab.";document.getElementById('agreeNotifyLabel').textContent="I understand that if this item gets lost or damaged, I would have to discuss a replacement with the lab administrator."}}}
async function finalCheckout(id){const checkoutForm=document.getElementById('form-object');const formContainer=document.getElementById('checkout-form');formContainer.style.display="none";const returnDate=document.getElementById('returnDate').value;const quantity=document.getElementById('quantity').value;let queryParams=`?itemId=${id}&quantity=${quantity}&returnDate=${returnDate}`;await fetch(`../backend/queries/checkout.php${queryParams}`).then((response)=>response.text()).then((result)=>{if(isJsonString(result))
result=JSON.parse(result);console.log(result)});checkoutForm.reset();await labItems(document.getElementById('lab-name').textContent,1,"")}
function isJsonString(str){try{const json=JSON.parse(str);return(typeof json==='object')}catch(e){return!1}}